#Configuration for different environments

defaults: &defaults
    first_name: John
    last_name: Stone
    email: support@advisorfeed.com
    password: q0UHFaA'zd
    aws_access_key_id: AKIAIFXHIBQNJEYRKQAA
    aws_secret_access_key: 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

development:
    <<: *defaults
    environment: Development
    s3_bucket_name: advisor_dev
    host: advisor_dev.s3-website-us-east-1.amazonaws.com

staging:
    <<: *defaults
    environment: Staging
    s3_bucket_name: advisor_stage
    host: advisor_stage.s3-website-us-east-1.amazonaws.com

production:
    <<: *defaults
    environment: Production
    s3_bucket_name: advisor_prod
    host: advisor_prod.s3-website-us-east-1.amazonaws.com

